CREATE DATABASE IF NOT EXISTS notebook;

CREATE TABLE IF NOT EXISTS notebook (
  id SERIAL PRIMARY KEY,
  title TEXT NOT NULL,
  content TEXT DEFAULT '' NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
