version: '3.8'

services:
  app:
    image: node:16.13.0
    container_name: nodejs-app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8000:8000"
      - "5173:5173"
    working_dir: /app
    environment:
      - NODE_ENV=development
    command: sh -c "npm config set cache /tmp --global && npm install && chmod 777 /app/node_modules && npm start"
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: 'notebook'
      MYSQL_USER: 'notebook'
      MYSQL_PASSWORD: 'pwd12345'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql

volumes:
  db-data:
